java_library(
    name = "jiffies",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon/src/main/java/jcarbon/data",
        "//src/jcarbon/src/main/java/jcarbon/util",
    ],
)
