java_library(
    name = "signal",
    visibility = ["//src/jcarbon-proto:__pkg__"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon-proto/src/main/java/jcarbon/linux",
        "//src/jcarbon-proto/src/main/java/jcarbon/linux/jiffies",
        "//src/jcarbon-proto/src/main/java/jcarbon/linux/powercap",
        "//src/jcarbon-proto/src/main/java/jcarbon/emissions",
        "//src/jcarbon-proto/src/main/java/jcarbon/rapl",
        "//src/jcarbon-proto/src/main/java/jcarbon/util",
        "//src/jcarbon-proto/src/main/proto/jcarbon/signal:signal_java_protos",
    ],
    exports = [
        "//src/jcarbon-proto/src/main/java/jcarbon/linux",
        "//src/jcarbon-proto/src/main/java/jcarbon/linux/jiffies",
        "//src/jcarbon-proto/src/main/java/jcarbon/linux/powercap",
        "//src/jcarbon-proto/src/main/java/jcarbon/emissions",
        "//src/jcarbon-proto/src/main/java/jcarbon/rapl",
        "//src/jcarbon-proto/src/main/java/jcarbon/util",
        "//src/jcarbon-proto/src/main/proto/jcarbon/signal:signal_java_protos",
    ]
)
