java_test(
    name = "DataOperationsTest",
    srcs = ["DataOperationsTest.java"],
    deps = ["//src/jcarbon"],
)

java_test(
    name = "TimeOperationsTest",
    srcs = ["TimeOperationsTest.java"],
    deps = ["//src/jcarbon"],
)
