java_library(
    name = "emissions",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon/src/main/java/jcarbon/util",
        "//src/jcarbon-proto/src/main/proto/jcarbon/signal:signal_java_protos",
    ],
    resources = ["//src/jcarbon/src/main/resources/emissions:emissions_data"],
)
