# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jcarbon_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15jcarbon_service.proto\x12\x0fjcarbon.service\"d\n\x0cStartRequest\x12\x17\n\nprocess_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1a\n\rperiod_millis\x18\x02 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_process_idB\x10\n\x0e_period_millis\"\x0f\n\rStartResponse\"5\n\x0bStopRequest\x12\x17\n\nprocess_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\r\n\x0b_process_id\"\x0e\n\x0cStopResponse\"_\n\x0b\x44umpRequest\x12\x17\n\nprocess_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x18\n\x0boutput_path\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_process_idB\x0e\n\x0c_output_path\"\x0e\n\x0c\x44umpResponse2\xe8\x01\n\x0eJCarbonService\x12H\n\x05Start\x12\x1d.jcarbon.service.StartRequest\x1a\x1e.jcarbon.service.StartResponse\"\x00\x12\x45\n\x04Stop\x12\x1c.jcarbon.service.StopRequest\x1a\x1d.jcarbon.service.StopResponse\"\x00\x12\x45\n\x04\x44ump\x12\x1c.jcarbon.service.DumpRequest\x1a\x1d.jcarbon.service.DumpResponse\"\x00\x42\x13\n\x0fjcarbon.serviceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jcarbon_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017jcarbon.serviceP\001'
  _globals['_STARTREQUEST']._serialized_start=42
  _globals['_STARTREQUEST']._serialized_end=142
  _globals['_STARTRESPONSE']._serialized_start=144
  _globals['_STARTRESPONSE']._serialized_end=159
  _globals['_STOPREQUEST']._serialized_start=161
  _globals['_STOPREQUEST']._serialized_end=214
  _globals['_STOPRESPONSE']._serialized_start=216
  _globals['_STOPRESPONSE']._serialized_end=230
  _globals['_DUMPREQUEST']._serialized_start=232
  _globals['_DUMPREQUEST']._serialized_end=327
  _globals['_DUMPRESPONSE']._serialized_start=329
  _globals['_DUMPRESPONSE']._serialized_end=343
  _globals['_JCARBONSERVICE']._serialized_start=346
  _globals['_JCARBONSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
