# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x0ejcarbon.signal\"\xd5\x03\n\x0eSignalInterval\x12<\n\x05start\x18\x01 \x01(\x0b\x32(.jcarbon.signal.SignalInterval.TimestampH\x00\x88\x01\x01\x12:\n\x03\x65nd\x18\x02 \x01(\x0b\x32(.jcarbon.signal.SignalInterval.TimestampH\x01\x88\x01\x01\x12\x37\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32).jcarbon.signal.SignalInterval.SignalData\x1a\x45\n\tTimestamp\x12\x11\n\x04secs\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x12\n\x05nanos\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x07\n\x05_secsB\x08\n\x06_nanos\x1a\xb6\x01\n\nSignalData\x12\x44\n\x08metadata\x18\x01 \x03(\x0b\x32\x32.jcarbon.signal.SignalInterval.SignalData.Metadata\x12\x12\n\x05value\x18\x02 \x01(\x01H\x00\x88\x01\x01\x1a\x44\n\x08Metadata\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_valueB\x08\n\x06_valueB\x08\n\x06_startB\x06\n\x04_end\"\xef\x01\n\x06Signal\x12.\n\x04unit\x18\x01 \x01(\x0e\x32\x1b.jcarbon.signal.Signal.UnitH\x00\x88\x01\x01\x12\x0e\n\x06source\x18\x02 \x03(\t\x12\x30\n\x08interval\x18\x03 \x03(\x0b\x32\x1e.jcarbon.signal.SignalInterval\"j\n\x04Unit\x12\x0c\n\x08\x41\x43TIVITY\x10\x00\x12\x10\n\x0cGRAMS_OF_CO2\x10\x01\x12\n\n\x06JOULES\x10\x02\x12\x0b\n\x07JIFFIES\x10\x03\x12\r\n\tMEGAHERTZ\x10\x04\x12\x0f\n\x0bNANOSECONDS\x10\x05\x12\t\n\x05WATTS\x10\x06\x42\x07\n\x05_unit\"\x8f\x01\n\tComponent\x12\x1b\n\x0e\x63omponent_type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x63omponent_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12&\n\x06signal\x18\x03 \x03(\x0b\x32\x16.jcarbon.signal.SignalB\x11\n\x0f_component_typeB\x0f\n\r_component_id\"6\n\x06Report\x12,\n\tcomponent\x18\x01 \x03(\x0b\x32\x19.jcarbon.signal.ComponentB\x12\n\x0ejcarbon.signalP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016jcarbon.signalP\001'
  _globals['_SIGNALINTERVAL']._serialized_start=33
  _globals['_SIGNALINTERVAL']._serialized_end=502
  _globals['_SIGNALINTERVAL_TIMESTAMP']._serialized_start=230
  _globals['_SIGNALINTERVAL_TIMESTAMP']._serialized_end=299
  _globals['_SIGNALINTERVAL_SIGNALDATA']._serialized_start=302
  _globals['_SIGNALINTERVAL_SIGNALDATA']._serialized_end=484
  _globals['_SIGNALINTERVAL_SIGNALDATA_METADATA']._serialized_start=406
  _globals['_SIGNALINTERVAL_SIGNALDATA_METADATA']._serialized_end=474
  _globals['_SIGNAL']._serialized_start=505
  _globals['_SIGNAL']._serialized_end=744
  _globals['_SIGNAL_UNIT']._serialized_start=629
  _globals['_SIGNAL_UNIT']._serialized_end=735
  _globals['_COMPONENT']._serialized_start=747
  _globals['_COMPONENT']._serialized_end=890
  _globals['_REPORT']._serialized_start=892
  _globals['_REPORT']._serialized_end=946
# @@protoc_insertion_point(module_scope)
