java_library(
    name = "jcarbon",
    visibility = ["//src/jcarbon:__pkg__"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon/src/main/java/jcarbon/cpu/eflect",
        "//src/jcarbon/src/main/java/jcarbon/cpu/jiffies",
        "//src/jcarbon/src/main/java/jcarbon/cpu/rapl",
        "//src/jcarbon/src/main/java/jcarbon/data",
        "//src/jcarbon/src/main/java/jcarbon/emissions",
        "//src/jcarbon/src/main/java/jcarbon/util",
    ],
    exports = [
        "//src/jcarbon/src/main/java/jcarbon/cpu/eflect",
        "//src/jcarbon/src/main/java/jcarbon/cpu/jiffies",
        "//src/jcarbon/src/main/java/jcarbon/cpu/rapl",
        "//src/jcarbon/src/main/java/jcarbon/data",
        "//src/jcarbon/src/main/java/jcarbon/emissions",
        "//src/jcarbon/src/main/java/jcarbon/util",
    ],
)
