java_library(
    name = "freq",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"], exclude=["Dvfs.java"]),
    deps = [
        "//src/jcarbon-proto/src/main/java/jcarbon/util",
        "//src/jcarbon-proto/src/main/proto/jcarbon/signal:signal_java_protos",
    ],
)
