java_library(
    name = "util",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon-proto/src/main/proto/jcarbon/signal:signal_java_protos"
    ],
    resources = ["//src/jcarbon-proto/src/main/c/jcarbon/util:libtime.so"],
)
