java_library(
    name = "jcarbon",
    visibility = ["//src/jcarbon:__pkg__"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon-proto/src/main/java/jcarbon/linux",
        "//src/jcarbon-proto/src/main/java/jcarbon/linux/jiffies",
        "//src/jcarbon-proto/src/main/java/jcarbon/linux/powercap",
        "//src/jcarbon-proto/src/main/java/jcarbon/emissions",
        "//src/jcarbon-proto/src/main/java/jcarbon/rapl",
        "//src/jcarbon-proto/src/main/java/jcarbon/util",
        "//src/jcarbon-proto/src/main/proto/jcarbon/signal:signal_java_protos",
    ],
    # exports = [
    #     "//src/jcarbon-proto/src/main/java/jcarbon/cpu/eflect",
    #     "//src/jcarbon-proto/src/main/java/jcarbon/cpu/jiffies",
    #     "//src/jcarbon-proto/src/main/java/jcarbon/cpu/rapl",
    #     "//src/jcarbon-proto/src/main/java/jcarbon/data",
    #     "//src/jcarbon-proto/src/main/java/jcarbon/emissions",
    #     "//src/jcarbon-proto/src/main/java/jcarbon/util",
    # ],
)
