java_library(
    name = "eflect",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/jcarbon/src/main/java/jcarbon/cpu",
        "//src/jcarbon/src/main/java/jcarbon/cpu/jiffies",
        "//src/jcarbon/src/main/java/jcarbon/cpu/rapl",
        "//src/jcarbon/src/main/java/jcarbon/data",
        "//src/jcarbon/src/main/java/jcarbon/util",
    ],
)
